const colors = require('tailwindcss/colors')

module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}",'./public/*.html','./components/**/*.{html,js}','./pages/**/*.{html,js}',],
  theme: {
    container: {
      center: true,
      padding: "2rem"
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',

      midnight: '#121063',
      metal: '#565584',
      tahiti: '#3ab7bf',
      silver:'#ecebff',
      bubblegum:'#ff77e9',
      bermuda: '#78dcca',
      coolgreen: "#228b22",
      black: "#000",
      white: "#fff",

      gray: colors.gray,

      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.lime,
      green: colors.green,
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      blue: colors.blue,
      indigo: colors.indigo,
      violet: colors.violet,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose,
  },
    extend: {
    //   colors: {
    //     transparent: 'transparent',
    //     current: 'currentColor',
    //     white: "#ffffff",
    //     purple: '#3f3cbb',
    //     midnight: '#121063',
    //     metal: '#565584',
    //     tahiti: '#3ab7bf',
    //     silver:'#ecebff',
    //     bubblegum:'#ff77e9',
    //     bermuda: '#78dcca',
    //     black: colors.black,
    //     red: colors.red,
    //     blue: colors.blue,
    //     green: colors.green,
    //     yellow: colors.yellow,
    //     orange: colors.orange,
    //     darkgray: colors.darkgray,
    //     pink: colors.pink,
    // },
  },
  },
  plugins: [],
}

// colors: {
//   transparent: 'transparent',
//   current: 'currentColor',
//   "#ffffff": colors.white,
//   '#3f3cbb': colors.purple,
//   '#121063': colors.midnight ,
//   '#565584': colors.metal,
//   '#3ab7bf': colors.tahiti,
//   '#ecebff': colors.silver,
//   '#ff77e9': colors.bubblegum,
//   '#78dcca': colors.bermuda,
//   black: colors.black,
//   red: colors.red,
//   blue: colors.blue,
//   green: colors.green,
//   yellow: colors.yellow,
//   orange: colors.orange,
//   darkgray: colors.darkgray,
//   purple: colors.purple,
//   pink: colors.pink,
// },