
services:
  api:
    build:
      context: /server
      dockerfile: Dockerfile
    # mem_limit: 128m
    hostname: api
    volumes:
      - ./server:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    links:
      - mysql
    ports:
      - "5000:5000"
  client:
    stdin_open: true
    build: 
      context: /client
      dockerfile: Dockerfile
    # mem_limit: 128m
    hostname: client

    volumes:
      - /frontend/node_modules
      - ./client:/frontend
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api
  mysql:
    image: mysql:8.0.28
    restart: always
    volumes:
      - ./mysql8:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_DATABASE: react_flask_mysql
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  nginx:
    build: 
      context: /nginx
      dockerfile: Dockerfile
    # mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
volumes:
  node-modules: