version: "3"
services:
  api:
    image: liamjdesmond84/react-flask-server
    # build:
    #   context: ./server
    #   dockerfile: Dockerfile
    # # command: ["flask", "run", "--host=0.0.0.0"]
    hostname: api
    restart: always
    volumes:
      - ./server:/backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
  client:
    image: liamjdesmond84/react-flask-client
    stdin_open: true
    # build: 
    #   context: ./client
    #   dockerfile: Dockerfile
    hostname: client
    volumes:
      - /frontend/node_modules
      - ./client:/frontend
    ports:
      - '3000:80'
    depends_on:
      - api
  mysql:
    image: mysql:8.0.28
    restart: always
    volumes:
      - ./mysql8:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_DATABASE: react_flask_mysql
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  
  # For use as a stand alone front API-Gateway
  
  # nginx:
  #   build: 
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   # mem_limit: 128m
  #   hostname: nginx
  #   restart: always
  #   volumes:
  #       - ./client/build:/usr/share/nginx/html
  #       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "80:80"
  #   depends_on:
  #       - api
  #       - client
volumes:
  node-modules:
