version: "3"
services:
  api:
    image: liamjdesmond84/react-flask-server
    # build:
    #   context: ./server
    #   dockerfile: Dockerfile
    # # command: ["flask", "run", "--host=0.0.0.0"]
    hostname: api
    restart: always
    environment:
      DB_HOST: your-rds-endpoint
      DB_PORT: 3306  # or the port your RDS instance is listening on
      DB_NAME: react_flask_mysql  # your database name
      DB_USER: your-rds-username
      DB_PASSWORD: your-rds-password
    ports:
      - "5000:5000"
    depends_on:
      - client

  client:
    image: liamjdesmond84/react-flask-client
    stdin_open: true
    # build: 
    #   context: ./client
    #   dockerfile: Dockerfile
    hostname: client
    volumes:
      - /frontend/node_modules
      - ./client:/frontend
    ports:
      - '3000:80'
    depends_on:
      - api

# Remove the mysql service as we're using RDS instead

# For use as a stand alone front API-Gateway

# nginx:
#   build: 
#     context: ./nginx
#     dockerfile: Dockerfile
#   # mem_limit: 128m
#   hostname: nginx
#   restart: always
#   volumes:
#       - ./client/build:/usr/share/nginx/html
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#   ports:
#     - "80:80"
#   depends_on:
#       - api
#       - client
