"""adding field

Revision ID: 0445c14196f0
Revises: d743f18ba156
Create Date: 2022-01-08 18:39:49.765415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0445c14196f0'
down_revision = 'd743f18ba156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bloggers', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bloggers', 'image')
    # ### end Alembic commands ###
